<?php 
	require('req/head_req.php');
	require('req/body_req.php');

	$context = "about_us";
?>
<? write_doctype(DT_TRANS); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<? write_title('About Us')?>
	<? write_metas('We are a organization that believes experiencing volunteering helps to find meaning in life and fulfilling emptiness. We are moved by the desire to help those less fortunately that us. We try and use the talents we and our volunteers bring to help improve the lives of those we help.', 'young,enthusiastic,joy,help,give,share,need,fulfill,compassion,talents,skills'); ?>
	<? write_css(ST_BASIC); ?>
	<? write_scripts(SC_FADE); ?>
	<? write_ga_snippet();?>
</head>
<body>
	<div id="header">
		<? write_main_menu($context) ?>
	</div>
	<div id="container">
		<div id="hdr_img">
			<? write_image_hdr($context); ?>
		</div>
		<div class="colmask rightmenu">
			<div class="colleft">
				<div class="col1wrap">
					<div class="col1">
						<!-- Column 1 start -->
						<h1><img src="img/logos/lets_go_volunteer.gif" alt="Let's Go Volunteer"/>About Us</h1>
						<hr/>
						<p>Let's go volunteer is a group of young, enthusiastic people who have discovered the joy of helping, giving and sharing with those in need. We believe that through the experience of volunteering and serving we can find meaning in our lives, thereby fulfilling the emptiness generated by the individualism and selfishness of modern society and learn about ourselves while expanding our horizons.</p>
						<h2>What moves us?</h2>
						<p>We are moved by those who are less fortunate, by children who don't go to school, by elderly people living in the street and by any human being in need of food, shelter or affection.</p>
						<h2>Why do something?</h2>
						<p>We believe in compassion, in giving and using our talents and skills to serve those who are in need. We know that loving, caring and helping others is the best way to thank life for all our blessings, give back to society and ultimately enjoy a more fulfilling existence.</p>
						<p>We know that love, creativity and a few resources can make a great difference in someone's life. </p>
						<h2></h2>
						<p>
							<ul>
								<li>To being a true and genuine help for other humans in need, to bringing real hope and to making a difference in their lives.</li>
								<li>To provide you with an opportunity of helping children, youth, elderly, homeless people, single mothers and in general less fortunate human beings.</li>
							    <li>To provide you with an amazing traveling experience, in a local way off the tourist track, where you will have a true cultural exchange that will leave your soul joyful.</li>
								<li>To your wellbeing, safety and fun.</li>
								<li>To offer you the chance to the improvement of your Spanish and communication skills.</li>
							</ul>
						</p>
						<!-- Column 1 end -->
					</div>
				</div>
				<div class="col2">
					<!-- Column 2 start -->
					<div class="quotes">
						<? write_quotes($context)?>
						<hr/>
						<? write_facebook_box($context)?>
						<hr/>
						<? write_vsa_box($context)?>
						<hr/>
						<? write_video_box($context)?>
					</div>
					<!-- Column 2 end -->
				</div>
		    </div>
		</div>
	</div>
	<div id="footer">
		<? write_footer_menu($context); ?>
	</div>
</body>
</html>
